name: Publish Logger

on:
  push:
    tags:
      - '[0-9]+.[0-9]+'

jobs:
  build:
    name: Release Logger
    runs-on: ubuntu-latest

    # job steps
    steps:
      # Setup of environment
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      # Prepare source code
      - name: Clone repo
        uses: actions/checkout@v2

      # Improve wrapper
      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      # Public Logger
      - name: Publish `logger-asamm`
        run: ./gradlew :clean :publishToMavenLocal
